[package]
name = "to_do_list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]


[dependencies]
cffi = "0.1.7"
cbindgen = "0.26.0"
lazy_static = "1.5.0"